# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetno', models.CharField(max_length=32)),
                ('asset_type', models.CharField(choices=[(b'server', '\u670d\u52a1\u5668'), (b'switch', '\u4ea4\u6362\u673a'), (b'router', '\u8def\u7531\u5668'), (b'firewall', '\u9632\u706b\u5899'), (b'storage', '\u5b58\u50a8\u8bbe\u5907'), (b'NLB', 'F5'), (b'wireless', '\u65e0\u7ebfAP'), (b'others', '\u5176\u5b83\u7c7b')], default=b'server', max_length=64, verbose_name='\u8d44\u4ea7\u7c7b\u578b')),
                ('sn', models.CharField(max_length=128, verbose_name='\u8d44\u4ea7SN\u53f7')),
                ('servermodel', models.CharField(max_length=64, verbose_name='\u8d44\u4ea7\u578b\u53f7')),
                ('business_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u7ba1\u7406IP')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='\u8fc7\u4fdd\u65e5\u671f')),
                ('business_unit', models.SmallIntegerField(choices=[(1, b'product'), (2, b'bete'), (3, b'cn|test'), (4, b'other')], default=1, verbose_name='\u751f\u4ea7\u73af\u5883')),
                ('tags', models.CharField(blank=True, max_length=128, verbose_name='\u8d44\u4ea7\u6807\u8bb0')),
                ('idc_cabinet', models.CharField(max_length=32, verbose_name='\u673a\u67dc\u53f7')),
                ('create_type', models.SmallIntegerField(choices=[(1, '\u4eba\u5de5'), (2, '\u81ea\u52a8')], default=2, verbose_name='\u6570\u636e\u65b9\u5f0f')),
                ('asset_status', models.SmallIntegerField(choices=[(1, '\u5728\u7ebf'), (2, '\u4e0b\u7ebf')], default=1, verbose_name='\u72b6\u6001')),
                ('reason', models.CharField(max_length=128, null=True)),
                ('release_date', models.CharField(max_length=32, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d44\u4ea7\u7ba1\u7406\u5458')),
            ],
            options={
                'verbose_name': '\u8d44\u4ea7\u603b\u8868',
                'verbose_name_plural': '\u8d44\u4ea7\u603b\u8868',
            },
        ),
        migrations.CreateModel(
            name='CmdbPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=32)),
                ('request_method', models.CharField(max_length=32)),
                ('request_args', models.CharField(max_length=64, null=True)),
                ('request_args_value', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpumodel', models.CharField(max_length=64, verbose_name='cpu\u578b\u53f7')),
                ('cpucount', models.SmallIntegerField(verbose_name='cpu\u4e2a\u6570')),
                ('cpucorecount', models.SmallIntegerField(verbose_name='cpu\u6838\u5fc3\u6570')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disktotalsize', models.CharField(max_length=32, verbose_name='\u78c1\u76d8\u5927\u5c0f')),
                ('diskcount', models.SmallIntegerField(verbose_name='\u78c1\u76d8\u4e2a\u6570')),
                ('diskraid', models.CharField(max_length=32, verbose_name='RAID')),
                ('df', models.TextField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(choices=[(1, '\u5e7f\u5dde\u5965\u98deIDC'), (2, '\u9999\u6e2fIDC'), (3, '\u6df1\u5733\u5357\u5c71IDC'), (4, '\u6df1\u5733\u5c97\u53a6IDC')], default=b'GZ', null=True, verbose_name='IDC\u540d\u79f0')),
                ('location', models.CharField(max_length=128, verbose_name='IDC\u4f4d\u7f6e')),
                ('contact_name', models.CharField(max_length=32, verbose_name='IDC\u8054\u7cfb\u4eba')),
                ('contact_tel', models.CharField(max_length=32, verbose_name='\u8054\u7cfb\u4eba\u7535\u8bdd')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorycount', models.SmallIntegerField(verbose_name='\u5185\u5b58\u4e2a\u6570')),
                ('memorysizeper', models.CharField(max_length=32, verbose_name='\u5355\u6761\u5185\u5b58\u5927\u5c0f')),
                ('memorytotal', models.CharField(max_length=32, verbose_name='\u5185\u5b58\u603b\u5927\u5c0f')),
                ('memory_slot_count', models.CharField(max_length=32, verbose_name='\u5185\u5b58\u63d2\u69fd\u4e2a\u6570')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osrelease', models.CharField(max_length=64, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('bip', models.GenericIPAddressField(verbose_name='\u4e1a\u52a1IP')),
                ('rip', models.GenericIPAddressField(default=b'0.0.0.0', verbose_name='\u7ba1\u7406IP')),
                ('uptime', models.CharField(max_length=64, verbose_name='\u8fd0\u884c\u65f6\u957f')),
                ('users', models.CharField(max_length=64)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CMDB_Server.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='\u5e94\u7528\u540d\u79f0')),
                ('crontab', models.TextField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB_Server.Server')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdbpermission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB_Server.CmdbPermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='memory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB_Server.Server'),
        ),
        migrations.AddField(
            model_name='disk',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB_Server.Server'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMDB_Server.Server'),
        ),
        migrations.AddField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CMDB_Server.IDC', verbose_name='IDC\u674b\u623f'),
        ),
    ]
